#! /bin/sh
java -classpath .:$CLASSPATH:/home/wyes/proj/cvt_proj/capnproto-java/runtime/target/classes:/home/wyes/proj/cvt_proj/capnproto-java/examples/target/classes:/home/wyes/proj/cvt_proj/grpc-java/core/build/classes/java/main:/home/wyes/proj/cvt_proj/grpc-java/stub/build/classes/java/main:/home/wyes/proj/cvt_proj/hybrid-msg-struct/helloworld HelloWorldMain "$@"
